# Generated by Django 4.2.11 on 2026-04-13 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True, verbose_name='ID датчика (TEMP_01, AIR_02 и т.д.)')),
                ('name', models.CharField(max_length=200, verbose_name='Название датчика')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота')),
                ('status', models.CharField(choices=[('active', '🟢 Активен'), ('inactive', '🔴 Неактивен'), ('error', '⚠️ Ошибка'), ('maintenance', '🔧 Техническое обслуживание')], default='active', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('threshold_critical', models.FloatField(help_text='Значение при котором срабатывает тревога', verbose_name='Критический порог')),
                ('threshold_warning', models.FloatField(blank=True, null=True, verbose_name='Пороговое значение предупреждения')),
                ('last_reading_value', models.FloatField(blank=True, null=True, verbose_name='Последнее показание')),
                ('last_reading_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего показания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'ordering': ['-is_active', 'sensor_id'],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('min_value', models.FloatField(default=0, verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(default=100, verbose_name='Максимальное значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип датчика',
                'verbose_name_plural': 'Типы датчиков',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_simulating', models.BooleanField(default=False, verbose_name='Имитировать показания')),
                ('simulation_interval', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Интервал имитации (секунды)')),
                ('simulation_min', models.FloatField(verbose_name='Минимальное значение при имитации')),
                ('simulation_max', models.FloatField(verbose_name='Максимальное значение при имитации')),
                ('noise_level', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Уровень шума (%)')),
                ('last_simulated', models.DateTimeField(blank=True, null=True, verbose_name='Последняя имитация')),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_config', to='sensors_app.sensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Конфигурация имитации',
                'verbose_name_plural': 'Конфигурации имитации',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensors_app.sensortype', verbose_name='Тип датчика'),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Критическое')),
                ('is_alert', models.BooleanField(default=False, help_text='True если значение выше порога критичности', verbose_name='Тревога')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время измерения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors_app.sensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('simple', 'Простая (Simple)'), ('moving_avg', 'Скользящее среднее (Moving Average)'), ('trend', 'Анализ тренда (Trend)'), ('adaptive', 'Адаптивная (Adaptive)')], default='simple', max_length=20, verbose_name='Тип стратегии')),
                ('moving_avg_window', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Окно скользящего среднего')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_strategy', to='sensors_app.sensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Стратегия анализа',
                'verbose_name_plural': 'Стратегии анализа',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение при срабатывании')),
                ('threshold', models.FloatField(verbose_name='Превышенный порог')),
                ('status', models.CharField(choices=[('new', '🆕 Новая'), ('acknowledged', '✅ Принята'), ('resolved', '✔️ Разрешена'), ('false_alarm', '❌ Ложная тревога')], default='new', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Принята')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Разрешена')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors_app.reading', verbose_name='Показание')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors_app.sensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Тревога',
                'verbose_name_plural': 'Тревоги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['sensor_id'], name='sensors_app_sensor__dfd3f2_idx'),
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['status'], name='sensors_app_status_c124ad_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor', '-timestamp'], name='sensors_app_sensor__f1eb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['is_alert', '-timestamp'], name='sensors_app_is_aler_750143_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='sensors_app_status_95791b_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['sensor', '-created_at'], name='sensors_app_sensor__b0367f_idx'),
        ),
    ]
